[
   {
     orientation: "fr",
     type: "paired-end",
     right reads: [
       "/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-3_Aligned.sortedByCoord.out_R2.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-2_Aligned.sortedByCoord.out_R2.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/NTT2-2_Aligned.sortedByCoord.out_R2.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-5_Aligned.sortedByCoord.out_R2.fastq.gz",
     ],
     left reads: [
       "/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-3_Aligned.sortedByCoord.out_R1.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-2_Aligned.sortedByCoord.out_R1.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/NTT2-2_Aligned.sortedByCoord.out_R1.fastq.gz",
"/fs/project/PAS0471/jelmer/assist/2022-02_fred/results//subset/map2virus/bam2fq/ATT1-5_Aligned.sortedByCoord.out_R1.fastq.gz",
     ]
   },
]
